### ISSUE TITLE
[improvement] Keep original name together with hash in resource name

### ISSUE THREAD

**Issue by almilo** [bclinkinbeard/resrcify#2]
Hashing the names of the processed resources has obviously the advantage of avoiding name conflicts when copying resources into same folder and allows also more effective caching.

But when it comes to debugging what is being loaded in the browser, it would be nice to at least partially see which resource each originally was.

Now:         "./logo.png" => "f23fafdeg12312.png"
Improved: "./logo.png" => "logo-f23fafdeg12312.png"

**Comment by bclinkinbeard** [comment]
I like this idea. Will try to get it in soon.

**Comment by kidoman** [comment]
Wow! This is insane... I just implemented this and was looking to open a PR. And bam! What a coincidence.

**Comment by bclinkinbeard** [comment]
Send it on over. :)

**Comment by kidoman** [comment]
One question: should I send a PR which makes this the default case (which I prefer, as it has no drawbacks, and makes the 80% case clearer) or as an option?

**Comment by kidoman** [comment]
Done!

**Comment by bclinkinbeard** [comment]
Closing in favor of #3
