### ISSUE TITLE
How will this work?

### ISSUE THREAD

**Issue by kidoman** [bclinkinbeard/resrcify#4]
Maybe I am having a brainfart, but how will this work:

https://github.com/bclinkinbeard/resrcify/blob/master/custom.js#L58

We declare `processed` in `resrc`, so it is always a empty map when line 58 hits. Correct?

**Comment by bclinkinbeard** [comment]
Ah, good catch. `resrc` was extracted from the main function recently, and I guess that got moved incorrectly. I will get it extracted soon.

**Comment by kidoman** [comment]
Ah alright!

Btw, ended up implementing [this](https://github.com/kidoman/sass-resrcify) based on your resrcify!

**Comment by bclinkinbeard** [comment]
Nice! `resrcify` is basically a port of [rework-assets](https://github.com/conradz/rework-assets). :)

This issue was fixed in https://github.com/bclinkinbeard/resrcify/commit/dad33190cacd0d81fc534917524f6e8811f2369c and shipped as 1.1.1
