### ISSUE TITLE
Wont direct use of resrc fail?

### ISSUE THREAD

**Issue by kidoman** [bclinkinbeard/resrcify#5]
In `atomify-css`, `resrc` is used directly.

https://github.com/atomify/atomify-css/blob/master/less.js#L4

Wont this code path result in `property` being undefined as it is [only](https://github.com/bclinkinbeard/resrcify/blob/master/custom.js#L18) initialised when `resrcify` is used as a `browserify` transform?

**Comment by bclinkinbeard** [comment]
Ah, true, guess we need to initialize it at the top too.

**Comment by bclinkinbeard** [comment]
Fixed in 1.1.3
